trigger:
  - develop
  - master

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
  demands: java

steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false

  - task: Npm@1
    displayName: 'npm Install mocha'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install -g mocha'

  - task: Npm@1
    displayName: 'npm install mocha-junit-reporter'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install -g mocha-junit-reporter'

  - bash: |
      # Write your commands here

      npm install -g serverless

    displayName: 'Bash Script'
    enabled: false

  - script: |
      npm test

       mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=./TEST-RESULTS.xml

    displayName: 'Unit Test'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '**/TEST-RESULTS.xml'

  - task: CopyFiles@2
    displayName: 'Copy Files to:  $(Build.ArtifactStagingDirectory)'
    inputs:
      TargetFolder: ' $(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: deploy
